## resume/CV Clean & Edit:

In [195]:
import PyPDF2, pdfplumber

In [196]:
#Target File
CV = "/Users/zhangyudan/Documents/Github/Proj5/data/YudanZhang_resume.pdf"
CV_File=open(CV,'rb')
Script=PyPDF2.PdfFileReader(CV_File)
pages=Script.numPages

Script = []
with pdfplumber.open(CV_File) as pdf:
    for i in range (0,pages):
        page=pdf.pages[i]
        text=page.extract_text()
        # print (text)
        Script.append(text)
        
Script=''.join(Script)
CV_Clear = Script.replace("\n","").replace('●', "")
CV_Clear

' Yudan Zhang  yz4346@columbia.edu   (814) 699-2653   www.linkedin.com/in/yudan-zhang-b75347229  EDUCATION  Columbia University   New York, NY  M.A.  in Statistics   Expected Dec. 2023  The Pennsylvania State University, University Park   State College, PA  B.S.  in Applied Statistics &  B.S.  in Economics, GPA:  3.69/4.00, Dean’s list                                                                  Aug. 2018 - May 2022  Coursework: Probability Theory, Applied Time Series & Regression Analysis, Stochastic Modeling and Survey Sampling  Econometrics, Labor Economics, and Decision Making & Strategy in Economics  SKILLS  Programming: R, Python, Minitab, SAS, Stata, Matlab, SQL, Github, LaTex,  Microsoft Office Suite  Language: Chinese, English  WORK EXPERIENCE  China Telecom Co.,Ltd. Beijing Research Institute   Remote  Intern Algorithm Engineer                                                                                                                                                    Jul. 2022 - Current     Developing machine learning model for price elasticity & coupon recommendation.     Assisting in literature reviews for future report use.  Risk Management Department at Bohai Securities   Tianjin, China  Implemented workflow automation using R & Python to assist senior risk management group                                   May 2021 - Aug. 2021     Designed and developed programs for 1) bond default rate supervision to cut potential losses, 2) crawling intraday valuation of  funds from online then auto-generating Excel spreadsheet, and 3) automating summary tables of certain bond indexes and  visualizing trends.     Cleaned, screened, and analyzed data of timely payments and bond defaults from 2019 to 2021 by self-developed programs.  Identified the characteristics of the past bond default to optimize the bond selection and therefore, lower default risk.     Calculated risk control indexes of a large sample of bonds by programing, made comparisons with industry-featured indexes and  the population mean of the bond market in China; assisted in adjusting and defining the quota of bonds.  R Shiny Application Programs: BOAST and iPRACTISE   PSU, PA  Research Assistant,  supervisor: Dr. Dennis Pearl,  Dr. Neil Hatfield  &  Dr. Sy-Miin Chow   May 2021 – May 2022     Developed a new interactive web app for statistics concept, Maximum Likelihood Estimation, with a concentration on the design  and coding of 1) the webpage structure and 2) interactive game, Escape Room.     Revised code & structure of web apps to increase accessibility, shorten the loading time, and ensure LaTex text display correctly.     Maintained databases (.csv, .excel & .rds) for adaptive tests and digital training resources.  Research on Influencing Factors of Consumption at Starbucks in Mainland China   Remote  Research Assistant,  supervisor: Prof. Omeed Selbe from the University of Southern California   Jun. 2020 – Aug. 2020     Designed questionnaires to collect features of customers for further analysis.     Assisted in preliminary data cleaning of 262 questionnaires, chi-square test, and cross analysis to verify the relationship between  variables and consumer behaviors using R & Stata.     Conducted literature reviews and writing meeting memos.  RELEVANT PROJECTS  Columbia University:  Weakly supervised learning: label noise & correction     Collaborated with the team to build 2 image classification models based on the baseline logistic regression model by Python.     U  sed neural network methods with transfer learning  and label correction techniques to achieve a final accuracy to 70%.  Columbia University:  Philosophy Data Project     Performed EDA of philosophy texts dataset which contains over 300,000 sentences from over 50 texts spanning 10 major  schools of philosophy on R notebook.     Detected interesting findings in tone, word use and sentence structure between author / schools using data visualization (word  cloud & sentimental analysis) and text mining techniques.  Penn State:  Reddit Posts Topics Classification with  DNN Embeddings     Built R-based prediction model which utilizes dimension reduction techniques (tsne & pca) and some machine learning  algorithms (e.g. xgboost classification) to determine which subreddit comments originated from.     Achieved an average score of 0.06603 for prediction, the top-two accuracy compared to the other 285 results.  PUBLICATION  Hanyu Meng, Wanting Lu, Jiayi Jin, Yudan Zhang, Ningxin Li, Influencing Factors of Consumption at Starbucks in Mainland China,  Frontiers in Economics and Management  , 2020,12, 1,  310-320 DOI:  10.6981/FEM.202012_1(12).0049 '

## job searching based on input:

In [197]:
# test if successfully script info from website
import requests
agent = {'User-agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}
r = requests.get("https://www.linkedin.com/jobs/view/data-analyst-at-parsley-health-3385039452?refId=M8kI1Wa%2B8le267Tw1HteqA%3D%3D&trackingId=0cr1swLF7wVNfz1KztO9AA%3D%3D&position=3&pageNum=0&trk=public_jobs_jserp-result_search-card", headers = agent)
print(r.status_code)

200

In [198]:
import os
import urllib
import requests
from bs4 import BeautifulSoup
from collections import defaultdict
import pandas as pd
from datetime import datetime

In [199]:
# search inputs: 
title = input('Enter your desired position: ').strip()
location = input('Enter your desired location: ').strip()
no_pages = int(input('Enter the # of pages to scrape: '))


info = []
headers = {'User-agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}

for page in range(no_pages):
    getVars = {'keywords' : title, 'location' : location ,'sort' : 'date', 'start': str(no_pages*10)}
    url = ('https://www.linkedin.com/jobs/search?' + urllib.parse.urlencode(getVars))
    print(url)
    r = requests.get(url, headers=headers)
    html = r.content
    soup = BeautifulSoup(html, "html.parser")
    
    jobs = soup.find_all('div', class_ = 'base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card')
    
    for job in jobs:
        title = str(job.find('h3', class_='base-search-card__title').text.strip())
        company = str(job.find('h4', class_='base-search-card__subtitle').text.strip())
        post_date = datetime.strptime(job.find('time')['datetime'], '%Y-%m-%d').date()
        link = job.find('a', class_='base-card__full-link')['href']
        
        info.append([title,company,post_date,link])
    

info_dict_list = defaultdict(list)

cols = ['Job_title','Company','Job_posted_date','Link']
info_table = pd.DataFrame(info, columns = cols)
# sort by post date
info_table = info_table.sort_values(by = 'Job_posted_date', ascending = False).reset_index(drop=True)
info_table

Enter your desired position: data analyst
Enter your desired location: new York
Enter the # of pages to scrape: 1
https://www.linkedin.com/jobs/search?keywords=data+analyst&location=new+York&sort=date&start=10

,Job_title,Company,Job_posted_date,Link
0,Data Analyst,Parsley Health,2022-12-03,https://www.linkedin.com/jobs/view/data-analys...
1,"Analyst, Data and insights (Games)",The New York Times,2022-12-03,https://www.linkedin.com/jobs/view/analyst-dat...
2,Data Analyst,"Take-Two Interactive Software, Inc.",2022-12-02,https://www.linkedin.com/jobs/view/data-analys...
3,Data Analyst,The Walt Disney Company,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...
4,Data Analyst,FIRST,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...
5,Data Analyst,ADP,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...
6,Research – Data Visualization Analyst/Associate,Morgan Stanley,2022-12-01,https://www.linkedin.com/jobs/view/research-%E...
7,"Analyst, Data and Insights, Homepage",The New York Times,2022-12-01,https://www.linkedin.com/jobs/view/analyst-dat...
8,Data Analyst,American Technology Consulting - ATC,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...
9,Data Analyst (REMOTE),Foot Locker,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...
10,Data Analyst,Institutional Investor,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...
11,Media Data Analyst,Distinct North America,2022-11-29,https://www.linkedin.com/jobs/view/media-data-...
12,Data Analyst,ADP,2022-11-24,https://www.linkedin.com/jobs/view/data-analys...
13,Data Analyst,Maven Clinic,2022-11-22,https://www.linkedin.com/jobs/view/data-analys...
14,Data Analyst,Valon,2022-11-21,https://www.linkedin.com/jobs/view/data-analys...
15,Data Analyst,TikTok,2022-11-21,https://www.linkedin.com/jobs/view/data-analys...
16,Data Analyst,Tradeweb,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...
17,Data Analyst,Dow Jones,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...
18,Data Analyst,On Call Counsel,2022-11-16,https://www.linkedin.com/jobs/view/data-analys...
19,Data Analyst,LTK (formerly rewardStyle & LIKEtoKNOW.it),2022-11-16,https://www.linkedin.com/jobs/view/data-analys...
20,Data Analyst,FOODMatch,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...
21,Data Analyst,ODDITY,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...
22,Data Analyst - Hidden,Heyday,2022-11-08,https://www.linkedin.com/jobs/view/data-analys...
23,Data Analyst,Cover Whale,2022-11-08,https://www.linkedin.com/jobs/view/data-analys...
24,Data Analyst,JASCI Software,2022-10-23,https://www.linkedin.com/jobs/view/data-analys...

## match based on search

In [200]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [201]:
match_percent = []
for l in info_table['Link']: 
    
    # extract job description from 2nd webpage (ie, main page for each job post)
    r = requests.get(l, headers=headers)
    soup = BeautifulSoup(r.content, "html.parser")
    job_description = soup.find('div', class_='show-more-less-html__markup show-more-less-html__markup--clamp-after-5').text.replace("\n","")
    
    # calculate match percentage 
    Match_Test = [CV_Clear,job_description]
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(Match_Test)
    MatchPercentage = cosine_similarity(count_matrix)[0][1]*100
    match_percent.append(MatchPercentage)
    
match_percent

[62.09931667926374,
 68.06115361835232,
 64.22884862922037,
 66.02313052308004,
 63.11811745098256,
 62.1862750955983,
 64.38827731319061,
 68.58002574281848,
 53.188206281337024,
 60.055209092995,
 65.80969184413976,
 60.66633817741175,
 63.00128683936909,
 63.034861993705235,
 61.856989965979444,
 63.0536138862592,
 69.18362258643941,
 65.47935875624393,
 39.139572483761356,
 67.7231463102024,
 67.41500922982657,
 65.52420213915431,
 63.132617344465345,
 60.91755603681966,
 65.28233368096559]

In [203]:
match_percent = pd.DataFrame(match_percent, columns = ['Matching_percentage'])
final_info_table = pd.concat([info_table, match_percent], axis=1)

# export tp csv file: 
final_info_table.to_csv(r'/Users/zhangyudan/Documents/Github/Proj5/data/final_info_table.csv', index=False)
final_info_table

,Job_title,Company,Job_posted_date,Link,Matching_percentage
0,Data Analyst,Parsley Health,2022-12-03,https://www.linkedin.com/jobs/view/data-analys...,62.099317
1,"Analyst, Data and insights (Games)",The New York Times,2022-12-03,https://www.linkedin.com/jobs/view/analyst-dat...,68.061154
2,Data Analyst,"Take-Two Interactive Software, Inc.",2022-12-02,https://www.linkedin.com/jobs/view/data-analys...,64.228849
3,Data Analyst,The Walt Disney Company,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...,66.023131
4,Data Analyst,FIRST,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...,63.118117
5,Data Analyst,ADP,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...,62.186275
6,Research – Data Visualization Analyst/Associate,Morgan Stanley,2022-12-01,https://www.linkedin.com/jobs/view/research-%E...,64.388277
7,"Analyst, Data and Insights, Homepage",The New York Times,2022-12-01,https://www.linkedin.com/jobs/view/analyst-dat...,68.580026
8,Data Analyst,American Technology Consulting - ATC,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...,53.188206
9,Data Analyst (REMOTE),Foot Locker,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...,60.055209
10,Data Analyst,Institutional Investor,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...,65.809692
11,Media Data Analyst,Distinct North America,2022-11-29,https://www.linkedin.com/jobs/view/media-data-...,60.666338
12,Data Analyst,ADP,2022-11-24,https://www.linkedin.com/jobs/view/data-analys...,63.001287
13,Data Analyst,Maven Clinic,2022-11-22,https://www.linkedin.com/jobs/view/data-analys...,63.034862
14,Data Analyst,Valon,2022-11-21,https://www.linkedin.com/jobs/view/data-analys...,61.856990
15,Data Analyst,TikTok,2022-11-21,https://www.linkedin.com/jobs/view/data-analys...,63.053614
16,Data Analyst,Tradeweb,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...,69.183623
17,Data Analyst,Dow Jones,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...,65.479359
18,Data Analyst,On Call Counsel,2022-11-16,https://www.linkedin.com/jobs/view/data-analys...,39.139572
19,Data Analyst,LTK (formerly rewardStyle & LIKEtoKNOW.it),2022-11-16,https://www.linkedin.com/jobs/view/data-analys...,67.723146
20,Data Analyst,FOODMatch,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...,67.415009
21,Data Analyst,ODDITY,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...,65.524202
22,Data Analyst - Hidden,Heyday,2022-11-08,https://www.linkedin.com/jobs/view/data-analys...,63.132617
23,Data Analyst,Cover Whale,2022-11-08,https://www.linkedin.com/jobs/view/data-analys...,60.917556
24,Data Analyst,JASCI Software,2022-10-23,https://www.linkedin.com/jobs/view/data-analys...,65.282334

In [204]:
print('Here are the top 10 recommended jobs based on your resume:')
final_info_table.nlargest(10,['Matching_percentage'])

Here are the top 10 recommended jobs based on your resume:

,Job_title,Company,Job_posted_date,Link,Matching_percentage
16,Data Analyst,Tradeweb,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...,69.183623
7,"Analyst, Data and Insights, Homepage",The New York Times,2022-12-01,https://www.linkedin.com/jobs/view/analyst-dat...,68.580026
1,"Analyst, Data and insights (Games)",The New York Times,2022-12-03,https://www.linkedin.com/jobs/view/analyst-dat...,68.061154
19,Data Analyst,LTK (formerly rewardStyle & LIKEtoKNOW.it),2022-11-16,https://www.linkedin.com/jobs/view/data-analys...,67.723146
20,Data Analyst,FOODMatch,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...,67.415009
3,Data Analyst,The Walt Disney Company,2022-12-01,https://www.linkedin.com/jobs/view/data-analys...,66.023131
10,Data Analyst,Institutional Investor,2022-11-30,https://www.linkedin.com/jobs/view/data-analys...,65.809692
21,Data Analyst,ODDITY,2022-11-09,https://www.linkedin.com/jobs/view/data-analys...,65.524202
17,Data Analyst,Dow Jones,2022-11-18,https://www.linkedin.com/jobs/view/data-analys...,65.479359
24,Data Analyst,JASCI Software,2022-10-23,https://www.linkedin.com/jobs/view/data-analys...,65.282334